name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: All tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set up MemCached
        run: docker run -d -it -p 11211:11211 memcached

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run tests
        run: go test -v  ./...